version: '3.7'
services:
  mongo_db:
    container_name: react_chat_mongo
    image: mongo:latest
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: 'chat_user'
      MONGO_INITDB_ROOT_PASSWORD: '12345678'
      MONGO_INITDB_DATABASE: 'test'
      MONGODB_ROOT_PASSWORD: '12345678'
    ports:
      - '3007:27017'
    expose: 
      - '27017'
    networks: 
      - chat_network
    volumes:
      - /var/lib/mongo-db-chat-volume:/data/db
      - /var/lib/mongo-chat-config-volume:/data/configdb

    
  redis_db:
    container_name: react_chat_redis
    image: redis:latest
    restart: always
    ports:
      - '3008:6379'
    expose:
      - '6379'
    networks: 
      - chat_network
    volumes:
      - /var/lib/redis-chat-volume:/data/


networks:
    chat_network:
        driver: bridge
volumes:
  redis-chat-volume:
  mongo-db-chat-volume:
  mongo-chat-config-volume:
